name: Pull Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Pull Docker image
      run: docker pull deeptidocker11/my-java-app:latest
      # Replace username/image_name:tag with the image name and tag you want to pull
